version: "1"

services:
  admin:
    build:
      context: ./frontend
      dockerfile: admin.Dockerfile
    ports:
      - 3000:80

  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./backend/migration/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
